name: Lint Code Style
on:
  - pull_request

jobs:
  lint:
    name: Code-Style Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Check Code Style
        run: |
          dotnet format Nickel.sln --verify-no-changes --exclude LegacyModLoader/
